# golangci-lint configuration
version: "2"

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  misspell:
    locale: US

linters:
  enable:
    - errcheck
    - goconst
    - gocritic
    - revive
    - govet
    - ineffassign
    - staticcheck
    - unused

formatters:
  enable:
    - gofmt
    - goimports

issues:
  exclude-rules:
    - path: _test.go
      linters:
        - errcheck
        - goconst
    - text: "avoid package names that conflict with Go standard library package names"
      linters:
        - revive
  max-issues-per-linter: 0
  max-same-issues: 0
