# golangci-lint configuration
version: "2"

linters:
  enable:
    - errcheck
    - goconst
    - gocritic
    - revive
    - govet
    - ineffassign
    - staticcheck
    - unused

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    misspell:
      locale: US

  exclusions:
    rules:
      - path: ".*_test\\.go"
        linters:
          - errcheck
          - goconst
      - text: "avoid package names that conflict with Go standard library package names"
        linters:
          - revive
      - text: "Error return value of.*is not checked"
        linters:
          - errcheck
        source: "_, _ = .*\\.Print"
      - text: "Error return value of `stream\\.Close` is not checked"
        linters:
          - errcheck
        source: "_ = stream\\.Close\\(\\)"

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
