apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
  labels:
    app: nginx
type: Opaque
stringData:
  username: admin
  password: secretpassword123
  api-key: "your-api-key-here"

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: mysql
type: Opaque
stringData:
  root-password: "MySecurePassword123!"
  database-password: "DbPassword456!"
  replication-password: "ReplPassword789!"

---
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    [Your TLS Certificate Here]
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    [Your TLS Private Key Here]
    -----END PRIVATE KEY-----

---
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "registry.example.com": {
          "username": "dockeruser",
          "password": "dockerpass",
          "email": "user@example.com"
        }
      }
    }
